### ISSUE TITLE
publishing

### ISSUE THREAD

**Issue by ghost** [CCorrado/Preston#6]
Not a real issue, but it seems you don't publish a stable version of your lib anywhere ? (jitpack or other).
I like your lib but i just want to get a proper way to integrate, thank you !

**Comment by CCorrado** [comment]
Hey Loïc, I'll try and get to this within the next few weeks. Need to add a maven publishing script for the library.

**Comment by CCorrado** [comment]
@loicteillard I wrote the script to upload today. Add this to your app/build.gradle dependencies block:

`implementation 'com.ccorrads:rxPreston:1.1.0'`

**Comment by ghost** [comment]
Thank you but unfortunately not working :( 
gradle is happy, compiling ok but the classes are not found.

After going deeper to understand, the maven repo exists but the aar downloaded seems empty (classes are missing) ?

**Comment by CCorrado** [comment]
ok, it might be the script not adding the compiled classes. I have a PR up #8 with the changes i made so i can play around with the AAR that gets generated.
