### ISSUE TITLE
events

### ISSUE THREAD

**Issue by ghost** [CCorrado/Preston#7]
i need to add an action after sound is complete, how to catch this event please ? (seems a rx question, but can't figure out to handle the oncomplete of mediaPlayerObserver)

**Comment by CCorrado** [comment]
This is definitely possible. You can create your own observable that extends `MediaPlayerObservable` and pass it in when you build the `MediaPlayerService`

```
class CustomMediaPlayerObserver : MediaPlayerObserver {
    override fun onSubscribe(disposable: Disposable) {
        super.onSubscribe()
    }

    override fun onNext(mediaPlayerState: MediaPlayerState) {
        super.onNext()
    }

    override fun onError(throwable: Throwable) {
        super.onError()
    }

    override fun onComplete() {
        super.onComplete
    }
}
```

**Comment by ghost** [comment]
Thanks, dont' forget to open class MediaPlayerObserver

**Comment by CCorrado** [comment]
Oh good point, I can do that.
